// <auto-generated />
namespace Picassi.Core.Accounts.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ReferenceChildCategories : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ReferenceChildCategories));
        
        string IMigrationMetadata.Id
        {
            get { return "201711251615581_ReferenceChildCategories"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
